#!/usr/bin/env bash

cd $SCRIPT_DIR
echo "HELLO FROM build libs: $SCRIPT_DIR"

if [ ! -d "$SOURCE" ]; then
  mkdir -p "$SOURCE"
fi

echo "Starting LIBXML2 build" >&2
if [ ! -f "$BUILD/lib/libxml2.so" ]; then
  $SCRIPT_DIR/build_libxml2
else
  echo "Found existing xml2" >&2
fi


