#!/usr/bin/env bash
set -euo pipefail
trap 'echo "ERROR: build failed in ${BASH_SOURCE[0]} at line ${LINENO}" >&2' ERR

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <project directory>" >&2
  exit 1
fi
if [ ! -d "$1" ]; then
  echo "Project directory $1 does not exist, please enter a valid directory" >&2
  exit 1
fi
if [[ ! -f "$1/pyproject.toml" && ! -f "$1/setup.py" ]]; then
  echo "Invalid Python project directory, did not find either pyproject.toml or setup.py in $1" >&2
  exit 1
fi

BASE="$PWD"
PROJECT_DIR="$(cd "$1" && pwd)"
echo "Project Directory: $PROJECT_DIR" >&2

export SOURCE="$BASE/source"
export BUILD="$BASE/build"
export BIN="$BASE/bin"
export SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export LD_RUN_PATH='$ORIGIN'
export ACLOCAL_PATH=/usr/share/aclocal
export LIBXML2_INCLUDE_DIRS="$BUILD/include/libxml2"
export LIBXML2_LIBRARIES="$BUILD/lib/libxml2.so"

if [ ! -d "$SOURCE" ]; then
  mkdir -p "$SOURCE"
fi

echo "Starting LIBXML2 build" >&2
if [ ! -f "$BUILD/lib/libxml2.so" ]; then
  "$SCRIPT_DIR/build_libxml2"
else
  echo "Found existing xml2" >&2
fi


venvs=("py310" "py311" "py312" "py313" "py314")
for venv in "${venvs[@]}"; do
  echo "Python venv: $venv" >&2
  if [ ! -d "$BASE/$venv" ]; then
    version="${venv:2}"
    version="${version:0:1}.${version:1}"
    echo "version $version"
    python${version} -m venv "$BASE/$venv"
    source "$BASE/$venv/bin/activate"
    pip install --upgrade pip
    deactivate
  fi
  source "$BASE/$venv/bin/activate"
  python --version

  pip install build auditwheel patchelf
  cd "$PROJECT_DIR"
  python -m build

  wheel=$(ls -1 dist/*${venv:2}*)
  echo $wheel
  case "$(uname -m)" in
    x86_64|amd64|i386|i686)
      echo "processor architecture is x86_64"
      auditwheel repair $wheel --plat manylinux_2_28_x86_64
      ;;
    aarch64|arm64|arm*)
      echo "processor architecture is aarch64"
      auditwheel repair $wheel --plat manylinux_2_28_aarch64
      ;;
    *)
      echo "ERROR: UNABLE TO BUILD WHEEL - Unknown architecture: $(uname -m)"
      exit 1
      ;;
  esac

  deactivate
done
