#!/bin/bash
pip install build
cd libonvif
python -m build
cd ../libavio
python -m build
cd ../liblivemedia
python -m build
cd ../onvif-gui
python -m build
cd ..
for FILE in libonvif/dist/*.whl; do pip install $FILE; done
for FILE in libavio/dist/*.whl; do pip install $FILE; done
for FILE in liblivemedia/dist/*.whl; do pip install $FILE; done
for FILE in onvif-gui/dist/*.whl; do pip install $FILE; done
