#!/bin/bash
find . -type f -name '._*' -delete
find . -type f -name '.DS_Store' -delete
cd libonvif

DIR=build
if [ -d "$DIR" ]; then
    rm -R build
fi
DIR=dist
if [ -d "$DIR" ]; then
    rm -R dist
fi
DIR=libonvif.egg-info
if [ -d "$DIR" ]; then
    rm -R libonvif.egg-info
fi

cd ../libavio
DIR=build
if [ -d "$DIR" ]; then
    rm -R build
fi
DIR=dist
if [ -d "$DIR" ]; then
    rm -R dist
fi
DIR=avio.egg-info
if [ -d "$DIR" ]; then
    rm -R avio.egg-info
fi

cd ../kankakee
DIR=build
if [ -d "$DIR" ]; then
    rm -R build
fi
DIR=dist
if [ -d "$DIR" ]; then
    rm -R dist
fi
DIR=kankakee.egg-info
if [ -d "$DIR" ]; then
    rm -R kankakee.egg-info
fi

cd ../onvif-gui
DIR=build
if [ -d "$DIR" ]; then
    rm -R build
fi
DIR=dist
if [ -d "$DIR" ]; then
    rm -R dist
fi
DIR=onvif_gui.egg-info
if [ -d "$DIR" ]; then
    rm -R onvif_gui.egg-info
fi

cd ..
