#!/bin/bash
find . -type f -name '._*' -delete
cd libonvif

FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=libonvif.egg-info
if [ -d "$FILE" ]; then
    rm -R libonvif.egg-info
fi

cd ../libavio
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=avio.egg-info
if [ -d "$FILE" ]; then
    rm -R avio.egg-info
fi

cd ../onvif-gui
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=onvif_gui.egg-info
if [ -d "$FILE" ]; then
    rm -R onvif_gui.egg-info
fi

cd ..
