#!/bin/bash

cd libonvif

FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=libonvif.egg-info
if [ -d "$FILE" ]; then
    rm -R libonvif.egg-info
fi
pip install -v .

cd ../libavio
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=avio.egg-info
if [ -d "$FILE" ]; then
    rm -R avio.egg-info
fi
pip install -v .

cd ../liblivemedia
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=liblivemedia.egg-info
if [ -d "$FILE" ]; then
    rm -R liblivemedia.egg-info
fi
pip install -v .

cd ../kankakee
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=kankakee.egg-info
if [ -d "$FILE" ]; then
    rm -R kankakee.egg-info
fi
pip install -v .

cd ../onvif-gui
FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=onvif_gui.egg-info
if [ -d "$FILE" ]; then
    rm -R onvif_gui.egg-info
fi
pip install .
cd ..
