#!/bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo >> $HOME/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew install wget automake nasm libtool pkgconfig cmake

cd $HOME/libonvif/scripts/mac

versions=("3.10.10" "3.11.9" "3.12.10" "3.13.12" "3.14.3")
for version in "${versions[@]}"; do
    ./install_python $version
done

source ./env_variables
./build_libxml2

cd $HOME/libonvif
first_pass=1
venvs=("py310" "py311" "py312" "py313" "py314")
for venv in "${venvs[@]}"; do
    source $HOME/$venv/bin/activate
    python --version
    if [ $first_pass == 1 ]; then
        cd $HOME/libonvif/libonvif
        pip install -v .
        cd $HOME/libonvif
        pyname=$(ls $HOME/$venv/lib | awk '{print $1}')
        pydir=$HOME/$venv/lib/$pyname/site-packages
        modname=$(ls $pydir/libonvif/libonvif*.so | awk '{print $1}')
        export executable=$modname
        export sourcedir=libonvif/libonvif
        scripts/mac/copy_libs
        scripts/mac/install_name
    fi
    first_pass=0
    pip uninstall -y libonvif
    cd $HOME/libonvif/libonvif
    pip install build
    python -m build
    deactivate
done
