#!/bin/bash

cd $HOME/libonivif/libonvif

echo "FUCKME"
echo $PWD

FILE=build
if [ -d "$FILE" ]; then
    rm -R build
fi
FILE=libonvif.egg-info
if [ -d "$FILE" ]; then
    rm -R libonvif.egg-info
fi
pip install -v .

cd ..
