#!/bin/bash


cd $HOME/libonvif/libonvif/scripts/linux_aarch64


source ./env_variables

#export LD_RUN_PATH='$ORIGIN'
#export ACLOCAL_PATH=/usr/share/aclocal
#export LIBXML2_INCLUDE_DIRS=$HOME/libxml2_build/include/libxml2
#export LIBXML2_LIBRARIES=$HOME/libxml2_build/lib/libxml2.so

#./make_build_dirs

rm -rf $HOME/libxml2_build
mkdir -p $HOME/libxml2_sources

#./build_libs

./build_libxml2

cd $HOME/libonvif
first_pass=1
#venvs=("py310" "py311" "py312" "py313" "py314")
venvs=("py313")
for venv in "${venvs[@]}"; do
  echo "venv: $venv"
  if [ ! -d "$HOME/$venv" ]; then
    echo "did not find venv $venv"
    version="${venv:2}"
    version="${version:0:1}.${version:1}"
    echo "version $version"
    python${version} -m venv $HOME/$venv
    . $HOME/$venv/bin/activate
    pip install --upgrade pip
    deactivate
  else
    echo "FOUND VENV $venv"
  fi
  source "$HOME/$venv/bin/activate"
  python --version
  if [ $first_pass == 1 ]; then
    echo "first pass"
    #$HOME/libonvif/libonvif/scripts/linux_aarch64/compile
    cd $HOME/libonvif/libonvif
    FILE=build
    if [ -d "$FILE" ]; then
      rm -R build
    fi
    FILE=libonvif.egg-info
    if [ -d "$FILE" ]; then
      rm -R libonvif.egg-info
    fi
    pip install -v .
    pyname=$(ls $HOME/$venv/lib | awk '{print $1}')
    pydir=$HOME/$venv/lib/$pyname/site-packages
    modname=$(ls $pydir/libonvif/libonvif*.so | awk '{print $1}')
    export executable=$modname
    export sourcedir=$HOME/libonvif/libonvif/libonvif
    $HOME/libonvif/libonvif/scripts/linux_aarch64/copy_libs
    pip uninstall -y libonvif
    rm -rf dist
  fi
  first_pass=0
  #$HOME/libonvif/libonvif/scripts/linux_aarch64/linux_pkgs
  cd $HOME/libonvif
  mkdir -p dist
  pip install build auditwheel patchelf
  cd $HOME/libonvif/libonvif
  rm -R dist
  python -m build
  auditwheel repair dist/*.whl --plat manylinux_2_26_aarch64
  mv wheelhouse/* ../dist
  mv dist/* ../dist
  deactivate
done
