#!/bin/bash

mkdir -p dist
pip install build auditwheel patchelf
cd $HOME/libonvif/libonvif
rm -R dist
python -m build
auditwheel repair dist/*.whl --plat manylinux_2_26_aarch64
mv wheelhouse/* ../dist
mv dist/* ../dist
cd ..
