#!/bin/bash


cd $HOME/libonvif/libonvif/scripts/linux_aarch64


source ./env_variables

mkdir -p $HOME/libxml2_sources
./build_libxml2

first_pass=1
#venvs=("py310" "py311" "py312" "py313" "py314")
venvs=("py313")
for venv in "${venvs[@]}"; do
  echo "venv: $venv"
  if [ ! -d "$HOME/$venv" ]; then
    echo "did not find venv $venv"
    version="${venv:2}"
    version="${version:0:1}.${version:1}"
    echo "version $version"
    python${version} -m venv $HOME/$venv
    . $HOME/$venv/bin/activate
    pip install --upgrade pip
    deactivate
  else
    echo "FOUND VENV $venv"
  fi
  source "$HOME/$venv/bin/activate"
  python --version
  if [ $first_pass == 1 ]; then
    echo "first pass"
    #$HOME/libonvif/libonvif/scripts/linux_aarch64/compile

    cd $HOME/libonvif/libonvif

    FILE=build
    if [ -d "$FILE" ]; then
        rm -R build
    fi
    FILE=libonvif.egg-info
    if [ -d "$FILE" ]; then
        rm -R libonvif.egg-info
    fi
    pip install -v .

    pyname=$(ls $HOME/$venv/lib | awk '{print $1}')
    pydir=$HOME/$venv/lib/$pyname/site-packages
    modname=$(ls $pydir/libonvif/libonvif*.so | awk '{print $1}')
    export executable=$modname
    export sourcedir=$HOME/libonvif/libonvif/libonvif
    $HOME/libonvif/libonvif/scripts/linux_aarch64/copy_libs
    pip uninstall -y libonvif
    rm -rf dist
  fi
  first_pass=0
  $HOME/libonvif/libonvif/scripts/linux_aarch64/linux_pkgs
  deactivate
done
