#!/usr/bin/env bash
set -euo pipefail

cd "$SOURCE"
git -C libxml2 pull 2> /dev/null || git clone --depth 1 https://github.com/GNOME/libxml2.git
cd libxml2
./autogen.sh  --prefix=$BUILD --without-python
make -j$(nproc)
make install
