#!/bin/bash

sudo apt install -y autoconf make wget g++ && \
sudo apt remove -y automake && \
mkdir -p $HOME/sources && cd ~/sources && \
if [ ! -d "automake-1.17" ]; then
    wget https://ftp.gnu.org/gnu/automake/automake-1.17.tar.gz &&\
    tar -xzf automake-1.17.tar.gz
fi && \
cd automake-1.17 && \
./configure && \
make && \
sudo make install && \
export ACLOCAL_PATH=/usr/share/aclocal && \
automake --version
