#!/bin/bash

cd $HOME/ffmpeg_sources && \
if [ ! -d "SDL-release-2.32.0" ]; then
    wget -O release-2.32.0.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.0.tar.gz && \
    tar xzvf release-2.32.0.tar.gz
fi && \
cd SDL-release-2.32.0 && \
./configure --prefix=$HOME/ffmpeg_build && \
make -j$(nproc) && \
make install
