#!/bin/bash

sudo apt install -y libssl-dev ninja-build && \
cd $HOME/sources && \
if [ ! -d "cmake-3.20.0" ]; then
    wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz && \
    tar -zxvf cmake-3.20.0.tar.gz
fi && \
cd cmake-3.20.0 && \
./bootstrap && \
make -j$(nproc) && \
sudo make install && \
cmake --version
