#!/bin/bash

cd $HOME/ffmpeg_sources && \
#wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/master.tar.bz2 && \
#tar xjvf x265.tar.bz2 && \
#cd multicoreware*/build/linux && \
#cd multicoreware-x265_git-ef83e1285847/build/linux
if [ ! -d "x265_4.1" ]; then
    wget http://ftp.videolan.org/pub/videolan/x265/x265_4.1.tar.gz && \
    tar xzvf x265_4.1.tar.gz
fi && \
cd x265_4.1/build/linux && \
PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED=on ../../source && \
PATH="$HOME/bin:$PATH" make  -j$(nproc) && \
make install
