#!/usr/bin/env bash

cd $DIR_NAME
echo "HELLO FROM build libs: $DIR_NAME"

if [ ! -d "$SOURCE" ]; then
  mkdir -p "$SOURCE"
fi

echo "Starting LIBXML2 build" >&2
if [ ! -f "$BUILD/lib/libxml2.so" ]; then
  $DIR_NAME/build_libxml2
else
  echo "Found existing xml2" >&2
fi


