#!/usr/bin/env bash

cd $DIR_NAME
echo "HELLO FROM build libs: $DIR_NAME"


if [ ! -d "$HOME/libxml2_sources" ]; then
  mkdir -p "$HOME/libxml2_sources"
fi
if [ ! -d "$HOME/ffmpeg_sources" ]; then
  mkdir -p "$HOME/ffmpeg_sources"
fi

echo "Starting LIBXML2 build" >&2
if [ ! -f "$HOME/libxml2_build/lib/libxml2.so" ]; then
  $DIR_NAME/build_libxml2
else
  echo "Found existing xml2" >&2
fi

echo "Starting LIB_X264 build" >&2
if [ ! -f "$HOME/ffmpeg_build/lib/libx264.so" ]; then
  $DIR_NAME/build_h264
else
  echo "Found existing x264" >&2
fi

echo "Starting LIB_X265 build" >&2
if [ ! -f "$HOME/ffmpeg_build/lib/libx265.so" ]; then
  $DIR_NAME/build_h265
else
  echo "Found existing x265" >&2
fi

echo "Starting FDK_AAC build" >&2
if [ ! -f "$HOME/ffmpeg_build/lib/libfdk-aac.so" ]; then
  $DIR_NAME/build_aac
else
  echo "Found existing AAC" >&2
fi

echo "Starting LIB_SDL2 build" >&2
if [ ! -f "$HOME/ffmpeg_build/lib/libSDL2.so" ]; then
  $DIR_NAME/build_sdl2
else
  echo "Found existing SDL2" >&2
fi

echo "Starting FFMPEG build" >&2
if [ ! -f "$HOME/ffmpeg_build/lib/libavcodec.so" ]; then
  $DIR_NAME/build_ffmpeg
else
  echo "Found existing FFMPEG" >&2
fi


