#!/bin/bash

cd $SOURCE && \
git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
cd fdk-aac && \
autoreconf -fiv && \
./configure --prefix="$BUILD" --enable-shared && \
make -j$(nproc) && \
make install
